### ISSUE TITLE
Error response from daemon: unable to find user phper: no matching entries in passwd file

### ISSUE THREAD

**Issue by minhkhoablieu** [ucan-lab/docker-laravel#268]
I'm run make install with root user

It show error: Error response from daemon: unable to find user phper: no matching entries in passwd file

![image](https://github.com/ucan-lab/docker-laravel/assets/12608657/65403891-cdc5-4ec8-b992-6a5f9a84a1c0)

Please help me. Thanks

**Comment by ucan-lab** [comment]
@minhkhoablieu 
This is the effect that was addressed in this issue #258
It is now possible to run it as a general user, but on the other hand, it seems that an error will occur in the Dockerfile because a root user cannot create a phper user with UID=0.

If you are in a hurry, running Docker as a general user should resolve the issue.
Or, the [v2.5.1](https://github.com/ucan-lab/docker-laravel/releases/tag/v2.5.1) version should work, so please try this.

I will consider whether it is possible to make it work even for the root user, or whether it should be supported.

**Comment by minhkhoablieu** [comment]
My execution environment is:

* Ubuntu 22.04
* User = root
* UID = 0
* GID = 0

I have created a new user, and it ran successfully, thank you.

**Comment by ucan-lab** [comment]
It's a late response, but once this PR(#277) is merged, it should be possible to build it as a root user or a non-root user.
